1.Bag of words

In [1]:
import kagglehub


path = kagglehub.dataset_download("goyaladi/twitter-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'twitter-dataset' dataset.
Path to dataset files: /kaggle/input/twitter-dataset


In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [4]:
bow=cv.fit_transform(df['text'])

In [5]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [6]:
bow=bow.toarray()

In [7]:
cv.transform(['Bappy watch dswithbappy']).toarray()


array([[0, 1, 0, 1, 0]])

In [8]:
X = bow
y = df['output']


# N-grams

In [9]:

# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [10]:
bow=cv.fit_transform(df['text'])

In [11]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


# TF-IDF (Term frequency- Inverse document frequency)

In [15]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df


text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [17]:
arr=tfidf.fit_transform(df['text']).toarray()

In [18]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [19]:
print(tfidf.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]


#word2vec

In [25]:
!pip install gensim

In [28]:
!pip install --upgrade gensim --user

In [20]:

import numpy as np
import pandas as pd
import gensim
import os

In [33]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [34]:
story = []
for filename in os.listdir('/content/data'):
    if filename == '.ipynb_checkpoints':
      pass
    f = open(os.path.join('/content/data',filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [35]:
story

[['human',
  'resource',
  'management',
  'foundations',
  'and',
  'the',
  'heart',
  'of',
  'organizational',
  'success',
  'what',
  'is',
  'human',
  'resource',
  'management',
  'hrm'],
 ['hrm',
  'is',
  'the',
  'strategic',
  'approach',
  'to',
  'managing',
  'people',
  'effectively',
  'to',
  'help',
  'an',
  'organization',
  'achieve',
  'its',
  'goals'],
 ['it',
  'involves',
  'recruiting',
  'developing',
  'motivating',
  'and',
  'retaining',
  'employees',
  'while',
  'ensuring',
  'compliance',
  'with',
  'labor',
  'laws'],
 ['human',
  'resource',
  'management',
  'is',
  'the',
  'process',
  'of',
  'acquiring',
  'training',
  'appraising',
  'and',
  'compensating',
  'employees',
  'and',
  'attending',
  'to',
  'their',
  'labor',
  'relations',
  'health',
  'safety',
  'and',
  'fairness',
  'concerns'],
 ['this',
  'holistic',
  'view',
  'emphasizes',
  'that',
  'hrm',
  'is',
  'not',
  'just',
  'about',
  'administrative',
  'tasks',
  

In [37]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [38]:
model.build_vocab(story)

In [39]:
model.train(story,total_examples=model.corpus_count, epochs= model.epochs)

(755, 3085)

In [46]:
model.wv.most_similar('your')

[('an', 0.2432500123977661),
 ('to', 0.2048126459121704),
 ('development', 0.19675219058990479),
 ('as', 0.1789841651916504),
 ('talent', 0.16231262683868408),
 ('compliance', 0.16071398556232452),
 ('capital', 0.15337981283664703),
 ('about', 0.14557865262031555),
 ('business', 0.1375400424003601),
 ('analyzing', 0.13327977061271667)]

In [43]:
print(model.wv.index_to_key)

['and', 'hr', 'to', 'the', 'employee', 'of', 'management', 'with', 'an', 'strategic', 'is', 'human', 'manager', 'are', 'they', 'managers', 'from', 'their', 'hrm', 'organizational', 'data', 'business', 'objectives', 'ethical', 'benefits', 'performance', 'talent', 'right', 'development', 'recruitment', 'employees', 'people', 'resource', 'turnover', 'empathy', 'as', 'leadership', 'work', 'engagement', 'at', 'workforce', 'key', 'competitive', 'conflicts', 'needs', 'capital', 'fostering', 'about', 'training', 'labor', 'compliance', 'it', 'your', 'for', 'analyzing', 'modern', 'thinking', 'decisions', 'like', 'retention', 'resignation', 'great', 'or', 'such', 'issues', 'making', 'policies', 'communication', 'effective', 'all', 'more', 'these', 'strategies', 'exit', 'legal', 'in', 'scope', 'staff', 'attract', 'culture', 'improving', 'growth', 'skills', 'functions', 'environment', 'administrative', 'fairness', 'relations', 'laws', 'ensuring', 'goals', 'organization', 'success']


In [50]:
model.wv['skills'].shape

(100,)

In [51]:

vec = model.wv.get_normed_vectors()

In [52]:
vec

array([[-0.00805395,  0.00845432,  0.08899293, ..., -0.12815791,
         0.02050153,  0.09985062],
       [-0.14765573,  0.06517193,  0.0897155 , ..., -0.04564979,
        -0.16058484,  0.07223596],
       [ 0.00220882,  0.05449261, -0.11818073, ...,  0.00643626,
         0.14494592, -0.12546793],
       ...,
       [ 0.10980088, -0.01139494, -0.07393227, ..., -0.13369632,
        -0.00671196, -0.07330064],
       [-0.0056447 ,  0.06481163, -0.12060942, ...,  0.02263265,
         0.10541084, -0.1375965 ],
       [-0.03436925, -0.08861773, -0.14712115, ..., -0.0240913 ,
         0.11821081,  0.01801571]], dtype=float32)

In [56]:
len(X)

4

In [57]:
X

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [59]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
X=pca.fit_transform(model.wv.get_normed_vectors())

In [60]:
X

array([[-0.22646172,  0.23935206],
       [ 0.07061711,  0.09293491],
       [-0.28181112, -0.1664386 ],
       [ 0.03402661,  0.00908431],
       [ 0.04388215, -0.36770004],
       [-0.25767782, -0.44025555],
       [ 0.17254603, -0.25501844],
       [ 0.04956897, -0.14590754],
       [-0.30597714,  0.0739103 ],
       [-0.12651624,  0.24929689],
       [ 0.16611294,  0.212004  ],
       [-0.1207735 , -0.08498432],
       [ 0.09762769,  0.21258223],
       [ 0.34276423, -0.32108036],
       [ 0.19998997,  0.08201248],
       [-0.18289027,  0.03017849],
       [-0.106525  , -0.03542438],
       [-0.00411108, -0.10520028],
       [-0.09387583,  0.1680194 ],
       [ 0.17289531, -0.0039038 ],
       [-0.43982595, -0.01679722],
       [ 0.3319317 , -0.08844843],
       [ 0.14399849, -0.00986714],
       [ 0.44805774,  0.11353015],
       [ 0.02796935,  0.12097639],
       [ 0.44481605, -0.30567846],
       [ 0.27097443, -0.11435008],
       [-0.26938012,  0.20642038],
       [ 0.2481477 ,